spring:
  application:
    name: review-service


  profiles:
    active: dev
server:
  port: 0
  forward-headers-strategy: framework

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  packages-to-scan: org.example.reviewservice
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8